### ISSUE TITLE
Questions about training.

### ISSUE THREAD

**Issue by yahooo-m** [MinghanLi/UniVS#3]
Great job! Since I only have a V100 for experiments, will this affect the training results?

**Comment by MinghanLi** [comment]
A single NVIDIA V100 is adequate for running inference with UniVS using R50 and SwinT backbones, matching the performance reported in the paper. However, with Swin-B and Swin-L backbones,  UniVS can only process 2-frame clips because of memory limitations. 

A single NVIDIA V100 cannot meet training requirements. If you want to finetuning UniVS based on our released pretrained models, you can try to freeze more layers to reduce the memory requirements. For your convenience, an example is provided below on how to freeze additional layers
````
CUDA_VISIBLE_DEVICES=0 python train_net.py \
  --num-gpus 1 \
  --dist-url tcp://127.0.0.1:50158 \
  --config-file configs/univs/univs_r50_stage2.yaml \
  SOLVER.IMS_PER_BATCH 1\
  SOLVER.BASE_LR 0.00001 \               # smaller learning rate is needed
  INPUT.SAMPLING_FRAME_NUM 3 \           # fewer frames in the input video clip
  INPUT.LSJ_AUG.SQUARE_ENABLED False \   # without square input 
  MODEL.BACKBONE.FREEZE_AT 5 \           # freeze all backbone layers
  MODEL.SEM_SEG_HEAD.FROZEN_PIXEL_DECODER True \  # freeze pixel encoder
  MODEL.SEM_SEG_HEAD.FROZEN_MASK_CONVS True \     # freeze the mask conv layer
  MODEL.SEM_SEG_HEAD.FROZEN_PREDICTOR False \     # Note that: unfreeze unified mask decoder 
  MODEL.WEIGHTS pretrained/univs_v2_cvpr/univs_r50_stage2.pth \
```

**Comment by yahooo-m** [comment]
Thanks for your reply!
And I apologize for the misunderstanding, I have some V100 GPUs available for use.

**Comment by MinghanLi** [comment]
BTW, our experiments show that on V100 GPUs with 32GB, when processing a 3-frame video clip, it is only necessary to freeze the backbone weights for R50 and SwinT. For SwinB and SwinL, however, we must also freeze the weights of the pixel encoder.

**Comment by yahooo-m** [comment]
Thanks！
